### ISSUE TITLE
Confirmed working + thanks

### ISSUE THREAD

**Issue by ryanamannion** [whoenig/thinkpad-p14s-gen2-ubuntu#1]
Setup: P14s Gen 2, Ubuntu 20.04 with kernel `5.13.1-051301-generic`

First off, thanks for summarizing/ combining all this into one repo. I've managed to do most of these things already, but the CPU throttling has been a huge pain in my side for a while now.

Using `s-tui` in stress mode shows that I can now get CPU frequencies above 400 MHz under heavy load, which is a welcome change. It may also be helpful to add the [info from user faustusdotbe about Intel Speedstep being enabled in the BIOS settings](https://github.com/erpalma/throttled/issues/265#issuecomment-920684950).

**Comment by whoenig** [comment]
Thanks for the feedback! I actually didn't find that setting in my BIOS. I am on 1.40; I think there is now also 1.42 with minor changes according to the changelog. If you changed that setting, could you point me to where to find it?

**Comment by ryanamannion** [comment]
I am on 1.41 I believe, and if I remember right it was under the `Power` menu, but I'll double check in a bit when I shut my computer down next. 

It was already set to `on` for me, but I figure somebody may potentially find the information useful. 

EDIT: Running BIOS v1.41 it is under `Config`>`Power`

**Comment by whoenig** [comment]
I also found it and refined the naming for the sleep state. Thanks for your help!

**Comment by ryanamannion** [comment]
Seems this isn't working as well as I naively thought. I am still having some real issues with throttling. I'll usually be ok from a cold start, but later in the day I will get all sorts of issues and throttle to 400 MHz even on relatively light single-threaded loads. 

Has your system been running smoothly?

**Comment by whoenig** [comment]
Seems to be working well and I rarely reboot (but I do use standby).
