### ISSUE TITLE
[Question] Anyone upgraded to 21.10 or 22.04 yet?

### ISSUE THREAD

**Issue by drvenabili** [whoenig/thinkpad-p14s-gen2-ubuntu#6]
Hi! I know this repo is specifically for 20.04, but I was on 21.04 (not an LTS), which reached end-of-life support. I was wondering if anyone upgraded to 21.10 and if yes, if new issues arose/were fixed?

Thanks

**Comment by whoenig** [comment]
Given that 22.04 is out, it might also interesting to gather information for that version (I haven't upgraded, yet).

**Comment by drvenabili** [comment]
Upgrade to 21.10 went without issue and all scripts within this repo work, so that's good. No magical thermal optimisation I was secretly hoping for though.

I'll do the upgrade to 22.04 LTS over the weekend and report back

**Comment by drvenabili** [comment]
Made the switch to 22.04, everything works fine.
